name: Add new issue to Backlog

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to backlog
    steps:
      - uses: actions/add-to-project@main
      - with:
        project-url: https://github.com/orgs/Lonsdaleite-I-O/projects/1
